global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'fitbit_exporter'
    static_configs:
      - targets: ['fitbit_exporter:8080']
  - job_name: 'fitbit_exporter_history'
    # scrape_interval: '999d'
    metrics_path: '/history'
    static_configs:
      - targets: ['fitbit_exporter:8080']


